### ISSUE TITLE
publishing new events at researchseminars

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/automation#19]
The token is already in the secrets, and their API is at https://researchseminars.org/api

**Comment by everthemore** [comment]
I propose a new python file, called from the register-new-zoom-talk bot, that using the API:

- Checks if the seminar series exists
- Creates it if not
- Edits the series to add the new timeslot *
- Create a new talk at that timeslot with all the info

* Not (yet) entirely sure if the series editing is necessary directly, or whether adding a talk with a timestamp (https://github.com/roed314/seminars/blob/master/Schema.md) is sufficient.

**Comment by everthemore** [comment]
Closed by #9

**Comment by akhmerov** [comment]
Reopening since we need to reenable it, and I think the code is buggy now (my linter complains about missing authorization argument right now).

**Comment by everthemore** [comment]
We should pick at least one of the topics listed here, for the SC (and LRC):
https://researchseminars.org/api/0/topics

**Comment by everthemore** [comment]
~~@akhmerov I'm testing the code we have again before pinging, since I can see some API items have been updated on the researchseminar side. I attempted to create a new seminarseries (id 'vsfspeakerscorner'), and am getting a success message. It may be that you have to confirm this when logging in, could you check (no rush)?~~ 
No longer required

WIP update on previous attempt:
The 'speakerscorner' seminar series exists, and when I use the API to add a talk I get a success message (+ the talk counter succesfully increases), but they do not show up (neither on the website, nor via other API requests to check talks).

**Comment by everthemore** [comment]
<img width="985" alt="Screenshot 2021-01-28 at 17 14 25" src="https://user-images.githubusercontent.com/1933169/106166281-4839df00-618c-11eb-8e68-b2e92a3efc54.png">

I managed to manually create the series in the meantime, and requested an API token myself for easier testing

**Comment by akhmerov** [comment]
I checked, and all the talks are there, just pending approval. We can do the following:

- Turn the API on
- Manually approve the talks
- After we ensure that everything works, request disabling manual approval
